# NumPY


# What is NumPy?
NumPy (Numerical Python) is a powerful Python library used for numerical computing. <br>
It provides support for:<br>
✅ Multidimensional arrays (ndarrays) <br>
✅ Mathematical operations like algebra, statistics, and random number generation <br>
✅ Fast performance with optimized C-based operations <br>

## 🔧 Why Use NumPy? <br>
✅ Faster than Python lists for large data <br>
✅ Memory efficient <br>
✅ Offers numerous built-in mathematical functions <br>
✅ Essential for scientific computing, data analysis, and machine learning <br>

In [4]:
import numpy as np
np.__version__

'1.26.4'

### Creating Your First NumPy Array

In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print("Type:", type(arr))   


[1 2 3 4 5]
Type: <class 'numpy.ndarray'>




### 🧩 **Key Differences Between NumPy Arrays and Python Lists**  

| Feature          | Python List | NumPy Array |
|------------------|--------------|----------------|
| **Speed**            | Slower          | Faster (optimized in C) |
| **Memory Efficiency** | Less efficient    | More efficient |
| **Mathematical Operations** | Loop-based         | Vectorized operations |
| **Convenience**      | Requires manual looping | Uses built-in methods |

---




## Creating NumPy Arrays
### ➤ Using np.array()


In [8]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array (Multidimensional)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", arr1)
print('\n')
print("2D Array:\n", arr2)
print('\n')
print("3D Array:\n", arr3)


1D Array:
 [1 2 3 4 5]


2D Array:
 [[1 2 3]
 [4 5 6]]


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### ➤ Using np.zeros()
Creates an array filled with zeros.

In [9]:
np.zeros((3, 3))  # 3x3 matrix of zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ➤ Using np.ones()

Creates an array filled with ones.

In [10]:
np.ones((2, 4))  # 2x4 matrix of ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### ➤ Using np.full()
Creates an array filled with a specific value.

In [ ]:
np.full((3, 3), 7)  # 3x3 matrix filled with 7

### ➤ Using np.arange()
Creates an array with values in a specified range.

In [13]:
np.arange(0, 10, 2) #(start,end+1, skipstep)


array([0, 2, 4, 6, 8])

### ➤ Using np.linspace()
Creates an array with evenly spaced values between a range.

In [17]:
np.linspace(0, 1, 5)  # (start,end, number of element)
 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### ➤ Using np.random for Random Arrays

In [21]:
np.random.random((3, 3))       # 3x3 array with random values (0 to 1)

array([[0.88815255, 0.00863846, 0.85108354],
       [0.45569641, 0.36126344, 0.33957853],
       [0.94534007, 0.54017429, 0.2160791 ]])

In [22]:
np.random.randint(1, 100, 5)   # Random integers between 1 and 100

array([33, 85, 29, 36, 84])

🔎 2. Array Properties
After creating an array, you can inspect its properties:

Property	Description	Example
.shape	Dimensions of the array	arr.shape → (3, 3)
.ndim	Number of dimensions	arr.ndim → 2
.size	Total number of elements	arr.size → 9
.dtype	Data type of elements	arr.dtype → int32
.itemsize	Size (in bytes) of each element	arr.itemsize → 4

In [23]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)
print("Item Size (bytes):", arr.itemsize)


Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Number of Dimensions: 2
Total Elements: 6
Data Type: int32
Item Size (bytes): 4
