# NumPY


# What is NumPy?
NumPy (Numerical Python) is a powerful Python library used for numerical computing. <br>
It provides support for:<br>
✅ Multidimensional arrays (ndarrays) <br>
✅ Mathematical operations like algebra, statistics, and random number generation <br>
✅ Fast performance with optimized C-based operations <br>

## 🔧 Why Use NumPy? <br>
✅ Faster than Python lists for large data <br>
✅ Memory efficient <br>
✅ Offers numerous built-in mathematical functions <br>
✅ Essential for scientific computing, data analysis, and machine learning <br>

In [4]:
import numpy as np
np.__version__

'1.26.4'

### Creating Your First NumPy Array

In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print("Type:", type(arr))   


[1 2 3 4 5]
Type: <class 'numpy.ndarray'>




### 🧩 **Key Differences Between NumPy Arrays and Python Lists**  

| Feature          | Python List | NumPy Array |
|------------------|--------------|----------------|
| **Speed**            | Slower          | Faster (optimized in C) |
| **Memory Efficiency** | Less efficient    | More efficient |
| **Mathematical Operations** | Loop-based         | Vectorized operations |
| **Convenience**      | Requires manual looping | Uses built-in methods |

---




## Creating NumPy Arrays
### ➤ Using np.array()


In [8]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array (Multidimensional)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", arr1)
print('\n')
print("2D Array:\n", arr2)
print('\n')
print("3D Array:\n", arr3)


1D Array:
 [1 2 3 4 5]


2D Array:
 [[1 2 3]
 [4 5 6]]


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
