# Indexing and Slicing in NumPy

##  1. Indexing in NumPy 🔎
NumPy uses zero-based indexing like Python lists.

### ➤ 1D Array Indexing

In [1]:
import numpy as np

In [3]:
arr = np.array([15,25,35,65,95])

print(arr[0]) # As usual first
print(arr[-1]) # Last
print(arr[2]) # n+1 th element

15
95
35


### ➤ 2D Array Indexing
For 2D arrays, use row index and column index.




In [4]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[1, 2])   # Element at 2nd row, 3rd column → 6
print(arr[0, 0])   # Element at 1st row, 1st column → 1


6
1


### ➤ 3D Array Indexing
For 3D arrays, use depth, row, and column indices.

In [8]:
arr = np.array([
    [[15,25],[35,69]],
    [[56,65],[56,89]],
    [[15,94],[55,77]]

    ])
print(arr)

[[[15 25]
  [35 69]]

 [[56 65]
  [56 89]]

 [[15 94]
  [55 77]]]


In [9]:
print(arr[0, 1, 1])  # Element at depth 0, row 1, column 1 → 4

69


# Slicing in NumPy

Slicing follows the pattern:

```array[start:stop:step] ```



### ➤ 1D Array Slicing

In [11]:
arr = np.array([10,50,56,69,96,78,15,45,35])

print(arr[1:4]) #from index 1 to 3
print(arr[:3])  # first three elements

[50 56 69]
[10 50 56]


In [13]:
print(arr[::2]) # every second element 
print(arr[::-1]) # reversed array

[10 56 96 15 35]
[35 45 15 78 96 69 56 50 10]


### ➤ 2D Array Slicing

In [15]:
arr = np.array([
    [15,64,9,6],
    [15,46,1,58],
    [5,63,98,78]
])

print(arr)

[[15 64  9  6]
 [15 46  1 58]
 [ 5 63 98 78]]


In [16]:
print(arr[1:,2:])  # Bottom-right corner

[[ 1 58]
 [98 78]]


In [17]:
print(arr[:2, 1:3])   # Top middle elements → 

[[64  9]
 [46  1]]


In [18]:
print(arr[:, 0])      # First column

[15 15  5]


In [20]:
print(arr[:, 3])      # 4th column

[ 6 58 78]


## 4. Fancy Indexing (Advanced Techniques) 🎯
Select multiple elements at once using a list of indices.

In [21]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]]) 


[10 30 50]


For 2D arrays:

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[[0, 2], [1, 2]])  #(row 0 col 1 and row 2 col 2
