# Reshaping and Manipulating Array in NumPy

## 1. Reshaping Arrays 🔄
Reshaping changes the shape (dimensions) of an array without changing its data.

### ➤ Reshape Method

In [2]:
import numpy as np

np.__version__

'1.26.4'

In [3]:
arr = np.array([1,8,9,6,9,63,78,69])

reshaped_arr = arr.reshape(3,2) # 3 columns , 2 reows

ValueError: cannot reshape array of size 8 into shape (3,2)

In [6]:
arr = np.array([1,8,9,6,9,63])

reshaped_arr = arr.reshape(3,2) # 3 columns , 2 reows

print(reshaped_arr)

[[ 1  8]
 [ 9  6]
 [ 9 63]]


### ➤ Reshape with -1 (Auto-dimension calculation)

In [ ]:
arr = np.array([1,8,9,6,9,63,78,69,98])

reshaped_arr = arr.reshape(3,-1) # Auto fills columns
print(reshaped_arr)

[[ 1  8  9]
 [ 6  9 63]
 [78 69 98]]


In [ ]:
arr = np.array([1,8,9,6,9,63,78,69])

reshaped_arr = arr.reshape(-1,2) # Auto fills rows
print(reshaped_arr)

[[ 1  8]
 [ 9  6]
 [ 9 63]
 [78 69]]


In [ ]:
arr = np.array([1,8,9,6,9,63,78,69,98])

reshaped_arr = arr.reshape(-1,-1) # specify atleast one dimension
print(reshaped_arr)

ValueError: can only specify one unknown dimension

### ➤ Flattening an Array
Converts a multi-dimensional array into a 1D array.

In [13]:
arr = np.array([[ 1 , 8],
 [ 9 , 6],
 [ 9,63],
 [78 ,69]])

print(arr.flatten())

[ 1  8  9  6  9 63 78 69]
