# Reshaping and Manipulating Array in NumPy

## 1. Reshaping Arrays 🔄
Reshaping changes the shape (dimensions) of an array without changing its data.

### ➤ Reshape Method

In [1]:
import numpy as np

np.__version__

'1.26.4'

In [2]:
arr = np.array([1,8,9,6,9,63,78,69])

reshaped_arr = arr.reshape(3,2) # 3 columns , 2 reows

ValueError: cannot reshape array of size 8 into shape (3,2)

In [3]:
arr = np.array([1,8,9,6,9,63])

reshaped_arr = arr.reshape(3,2) # 3 columns , 2 reows

print(reshaped_arr)

[[ 1  8]
 [ 9  6]
 [ 9 63]]


### ➤ Reshape with -1 (Auto-dimension calculation)

In [4]:
arr = np.array([1,8,9,6,9,63,78,69,98])

reshaped_arr = arr.reshape(3,-1) # Auto fills columns
print(reshaped_arr)

[[ 1  8  9]
 [ 6  9 63]
 [78 69 98]]


In [5]:
arr = np.array([1,8,9,6,9,63,78,69])

reshaped_arr = arr.reshape(-1,2) # Auto fills rows
print(reshaped_arr)

[[ 1  8]
 [ 9  6]
 [ 9 63]
 [78 69]]


In [6]:
arr = np.array([1,8,9,6,9,63,78,69,98])

reshaped_arr = arr.reshape(-1,-1) # specify atleast one dimension
print(reshaped_arr)

ValueError: can only specify one unknown dimension

### ➤ Flattening an Array
Converts a multi-dimensional array into a 1D array.

In [7]:
arr = np.array([[ 1 , 8],
 [ 9 , 6],
 [ 9,63],
 [78 ,69]])

print(arr.flatten())

[ 1  8  9  6  9 63 78 69]


### ➤ Ravel Method (More Efficient Flattening)
Unlike .flatten(), .ravel() returns a view rather than a copy.

In [8]:
print(arr.ravel())

[ 1  8  9  6  9 63 78 69]


**Difference**
1. Return Type:
    * flatten() always returns a copy of the array
    * ravel() returns a view of the original array when possible (more memory efficient)


2. Memory Usage:

    * flatten() allocates new memory for the flattened array
    * ravel() tries to avoid memory allocation by returning a view

In [9]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Using flatten()
flat_copy = arr.flatten()

# Using ravel()
flat_view = arr.ravel()




In [10]:
# Modify the flattened arrays
flat_copy[0] = 99
print("Original array after modifying flatten():", arr)

Original array after modifying flatten(): [[1 2 3]
 [4 5 6]]


##### Unchnaged as flat copy is an different element having separate memory

In [11]:
flat_view[0] = 88
print("Original array after modifying ravel():", arr)

Original array after modifying ravel(): [[88  2  3]
 [ 4  5  6]]


##  2. Transposing Arrays 
Transposing switches rows and columns.

### ➤ Using .T

In [12]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print(arr.T) # doesn't change the original one



[[1 3 5]
 [2 4 6]]



#  3. Stacking Arrays 🧩
Combines multiple arrays.

### ➤ Horizontal Stacking (hstack)



In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))  


[1 2 3 4 5 6]


➤ Vertical Stacking (vstack)

In [14]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[6,9]])

print(np.vstack((c,d)))

[[1 2]
 [3 4]
 [5 6]
 [6 9]]


The np.vstack() function vertically stacks arrays (row-wise). In this case, it's taking two 2×2 arrays and creating a 4×2 array by stacking them on top of each other.<br>

c is a 2×2 array (2 rows, 2 columns) <br>
d is a 2×2 array (2 rows, 2 columns) <br>
When you vertically stack them with np.vstack(), you're combining the rows while keeping the same number of columns:<br>

The result has 4 rows (2 from c + 2 from d)<br>
The result has 2 columns (same as both input arrays)<br>

# 4. Splitting Arrays✂️
Splitting divides an array into multiple parts

### ➤ Horizontal Split ✂️ 

In [15]:
arr = np.array([[5,6,6,7,9,10],[1,5,6,9,10,5]])

print(np.hsplit(arr,2))

[array([[5, 6, 6],
       [1, 5, 6]]), array([[ 7,  9, 10],
       [ 9, 10,  5]])]


In [16]:
arr

array([[ 5,  6,  6,  7,  9, 10],
       [ 1,  5,  6,  9, 10,  5]])

### ➤ Vertical Split

In [17]:
print(np.vsplit(arr,2))

[array([[ 5,  6,  6,  7,  9, 10]]), array([[ 1,  5,  6,  9, 10,  5]])]


## 🔄 5. Changing Data Types
NumPy allows conversion between data types.

### ➤ Example: Converting int to float

In [18]:
arr = np.array([1, 2, 3], dtype='int32')
float_arr = arr.astype('float64')

print(float_arr)     
print(float_arr.dtype)  


[1. 2. 3.]
float64
