# Random Number Generation and Statistical Functions in NumPy


 ## 1. Generating Random Numbers with np.random 🎲
The np.random module is used to generate random numbers efficiently.


### ➤ **Basic Random Number Functions**
| Function                     | Description                        | Example Output |
|-----------------------------|------------------------------------|-----------------|
| `np.random.random(size)`      | Random floats in range [0, 1)      | `[0.23 0.75 0.51]` |
| `np.random.randint(low, high, size)` | Random integers in range [low, high) | `[5 8 3]` |
| `np.random.rand(dim1, dim2)`  | Random floats in range [0, 1) with shape | `[[0.1 0.5] [0.9 0.2]]` |
| `np.random.randn(dim1, dim2)` | Random samples from **standard normal distribution** | `[[-1.2 0.8] [1.5 -0.3]]` |
| `np.random.choice(list)`      | Randomly picks values from a list  | `[3 1 5]` |

---




In [1]:
import numpy as np

In [8]:
# Generate a random float between 0 and 1
print(np.random.random())

0.680499677670569


In [ ]:
# Generate an array of random floats
print(np.random.random((3,4))) # np.random.random(size=(3,4))
# 3x4 array of random floats

[[0.42262409 0.68415566 0.05012964 0.40685472]
 [0.42080258 0.57203186 0.16383708 0.56558448]
 [0.46000115 0.61701878 0.88575529 0.42704034]]


##### Generate random integers between low and high
   5 random integers between 1 and 99

In [ ]:
# Generate random integers between low and high
random_ints = np.random.randint(low=1, high=100, size=5) 

print(random_ints) 

[17 75 48 76 96]


In [13]:
print(np.random.randint(20,200,12))

[165 122 100 132 128 102 159  44 115 162 151 176]


**Random Integers (between 1 and 10) in 3X3 a metrix** 

In [ ]:

print(np.random.randint(1, 10, (3, 3))) 

[[8 7 2]
 [6 7 3]
 [4 4 2]]


### Random Numbers from a Normal Distribution

In [15]:

print(np.random.randn(2, 3))

[[ 0.32876365 -1.53945362  1.01333097]
 [ 0.06048204 -1.18876383  0.54143872]]


#### Random Choice from List


In [16]:
print(np.random.choice([10, 20, 30, 40, 50], 3))

[30 10 50]
