#  **2. Statistical Functions in NumPy** 📊





NumPy provides various functions for **descriptive statistics**.

| Function         | Description                          |
|------------------|--------------------------------------|
| `np.mean()`        | Mean (average) of values             |
| `np.median()`      | Median of values                     |
| `np.std()`         | Standard deviation                   |
| `np.var()`         | Variance                             |
| `np.min()`         | Minimum value                        |
| `np.max()`         | Maximum value                        |
| `np.percentile()`  | nth percentile of array elements     |


 


In [1]:
import numpy as np

In [2]:
arr = np.array([4,5,9,7,8,9,2,5,15,69])

print("Mean:", np.mean(arr))

Mean: 13.3


In [3]:
print("Median:",np.median(arr))

Median: 7.5


In [4]:
print("Standard Deviation:",np.std(arr))

Standard Deviation: 18.87352643254567


In [5]:
print("Variance:",np.var(arr))

Variance: 356.21000000000004


In [6]:
print("min:",np.min(arr))


min: 2


In [7]:
print("Max:",np.max(arr))

Max: 69


In [9]:
print("90th percentile:", np.percentile(arr,90))

90th percentile: 20.39999999999998


#  **Sorting and Searching** 📉

### ➤ Sorting an Array

In [10]:
arr = np.array([5,9,6,7,2,6])

In [11]:
print(np.sort(arr))

[2 5 6 6 7 9]


### ➤ Searching for Elements

* ```np.where()``` → Returns the indices of elements that satisfy a condition.

* ```np.argmax()``` → Returns the index of the maximum value.

* ```np.argmin()``` → Returns the index of the minimum value.

In [16]:
print(arr)

[5 9 6 7 2 6]


In [14]:
print(np.where(arr>15))
print(np.where(arr>5))

(array([], dtype=int64),)
(array([1, 2, 3, 5], dtype=int64),)


In [15]:
print(np.argmax(arr))

1


In [17]:
print(np.argmin(arr))

4


### ✅ Practice Tasks
1. Generate a 3x3 random integer matrix with values between 1 and 100.

    * Find its mean, median, and standard deviation.

2. Create an array of 10 random numbers between 1 and 50 and sort them.

3. Create an array of 20 random numbers and filter all values greater than 25.

4. Generate a 4x4 matrix of random values from a normal distribution.